<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sys" ignored="0" name="Default test" tests="6" failures="1" timestamp="09 Jun 2020 23:42:31 GMT" time="6.855" errors="0">
  <testcase name="getweatherdetails" time="3.089" classname="restassuredtraining.GetValidatingJsonResponse"/>
  <testcase name="getweatherdetails" time="1.547" classname="restassuredtraining.GetWeatherDetailsJason">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;33.21 Degree celsius&amp;gt; but was:&amp;lt;33.42 Degree celsius&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<33.21 Degree celsius> but was:<33.42 Degree celsius>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at restassuredtraining.GetWeatherDetailsJason.getweatherdetails(GetWeatherDetailsJason.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getweatherdetails -->
  <testcase name="queryParameter" time="1.262" classname="restassuredtraining.QuearyParameter"/>
  <testcase name="getweatherdeatails" time="0.258" classname="restassuredtraining.GetRequest"/>
  <testcase name="getweatherdeatails" time="0.286" classname="restassuredtraining.GetRequest_allheaders"/>
  <testcase name="getweatherdeatails" time="0.356" classname="restassuredtraining.GetRequest_authorizationtest"/>
</testsuite> <!-- Default test -->
